
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 85
#define YY_END_OF_BUFFER 86
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[242] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   86,   84,
       76,   75,   53,   27,   52,   65,   84,   56,   57,   51,
       60,   51,   59,   52,   72,   72,   62,   58,   50,   61,
       50,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   63,   64,   84,
       66,   84,   67,   37,   38,   28,   85,   46,   45,   41,
       43,   42,   49,   48,    0,    0,   54,   73,   73,   39,
       44,    0,    0,    0,   72,    0,   68,   70,   50,   69,
       83,    0,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   17,   83,   83,   83,   83,   83,   83,   83,

       83,   83,   83,   83,   83,   83,   83,   83,   83,    0,
       47,   37,   36,   33,   30,   29,   32,   31,   34,   35,
       46,   41,   40,   74,    0,    0,    0,    0,    0,    0,
        0,    0,   73,    0,   72,    0,   72,    0,   73,   83,
       83,   83,   71,   83,   24,   83,   83,   83,   83,   83,
       20,    3,   83,   83,   83,   23,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   81,   78,   77,
       80,   79,   82,    0,   73,   73,   73,   72,   73,   73,
       72,   73,   83,    2,   83,   83,   83,   25,   18,   83,
       83,   13,   26,   83,   83,   83,   83,   83,   83,   16,

       83,   83,   12,   83,   73,    0,   73,    0,   73,   15,
        7,    5,   83,    4,   83,   83,   83,   83,   83,   83,
       83,   83,    6,   19,   83,   22,   83,   83,   10,   21,
       55,   11,   83,   83,    8,   83,    1,   14,   83,    9,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    6,    6,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       35,   42,   43,   44,   45,   46,   47,   35,   48,   49,
       50,   51,   52,    6,   53,    6,   54,   55,   56,   57,

       58,   59,   60,   61,   62,   35,   63,   64,   65,   66,
       67,   68,   35,   69,   70,   71,   72,   73,   74,   35,
       75,   76,   77,   78,   79,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[80] =
    {   0,
        1,    2,    3,    3,    4,    3,    3,    3,    3,    3,
        3,    5,    3,    3,    3,    6,    3,    7,    8,    8,
        3,    3,    3,    3,    3,    9,    9,    9,    9,    9,
        9,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,    3,
        4,    3,   11,    9,    9,    9,    9,    9,    9,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,    3,    3,    3
    } ;

static const flex_int16_t yy_base[255] =
    {   0,
        0,    0,   78,   79,  669,  668,   80,   83,  656,  672,
      672,  672,  624,  672,  672,  637,  583,  672,  672,  612,
      672,  608,   68,   77,   77,   81,  549,  672,   67,  545,
       78,  515,   54,  114,   61,   69,   96,  107,   91,  126,
       89,  127,  129,  141,  111,  119,  137,  672,  672,  513,
      672,  487,  672,    0,  672,  672,  212,    0,  672,    0,
      672,  547,  672,  672,  553,  277,  672,  177,  190,  672,
      672,  100,   89,  545,  195,  186,  672,  672,  672,  672,
      507,    0,  173,  192,  213,  193,  184,  206,  223,  187,
      212,  222,  505,  240,  234,  237,  235,  252,  262,  265,

      257,  264,  277,  272,  286,  280,  303,  304,  504,  499,
      672,    0,  672,  672,  672,  672,  672,  672,  672,  672,
        0,    0,  672,  672,  523,  517,  515,  514,  511,  506,
      209,  332,  340,   94,  345,  491,  469,   96,  349,  428,
      318,  320,  426,  332,  422,  333,  335,  331,  351,  329,
      373,  359,  355,  346,  341,  300,  347,  366,  358,  368,
      386,  370,  375,  394,  389,  396,  390,  672,  672,  672,
      672,  672,  672,  133,  412,  169,  174,  417,  323,  317,
      306,  439,  398,  259,  395,  402,  416,  256,  245,  418,
      419,  241,  224,  434,  438,  430,  424,  427,  442,  221,

      445,  431,  219,  452,  481,  373,  378,  226,  223,  185,
      183,  180,  464,  171,  453,  463,  480,  484,  472,  482,
      490,  489,  169,  165,  476,  159,  492,  500,  151,  130,
      113,   93,  496,  498,   75,  501,   73,   71,  510,   68,
      672,  571,  582,  593,  602,  607,  610,  621,  632,  643,
      649,  652,  656,  660
    } ;

static const flex_int16_t yy_def[255] =
    {   0,
      241,    1,  242,  242,  243,  243,  244,  244,  241,  241,
      241,  241,  241,  241,  241,  241,  245,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  241,  241,  247,
      241,  241,  241,  248,  241,  241,  241,  249,  241,  250,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  251,  241,  241,  241,  241,  241,  241,
      246,  252,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,

      246,  246,  246,  246,  246,  246,  246,  246,  246,  247,
      241,  248,  241,  241,  241,  241,  241,  241,  241,  241,
      249,  250,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  253,  254,  241,  241,  252,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  253,  253,
      254,  241,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,

      246,  246,  246,  246,  241,  241,  241,  253,  253,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
        0,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241
    } ;

static const flex_int16_t yy_nxt[752] =
    {   0,
       10,   11,   12,   13,   14,   10,   15,   16,   17,   18,
       19,   15,   20,   21,   22,   23,   24,   25,   26,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   32,   35,
       36,   32,   32,   37,   32,   32,   38,   39,   40,   32,
       41,   42,   43,   44,   45,   46,   47,   32,   32,   48,
       10,   49,   50,   32,   33,   34,   32,   35,   36,   32,
       32,   37,   32,   38,   39,   40,   32,   41,   42,   43,
       44,   45,   46,   47,   32,   32,   51,   52,   53,   55,
       55,   61,   56,   56,   61,   68,   69,   69,   70,   78,
       79,   62,   72,   71,   62,   83,   72,   90,   75,   75,

       75,   79,   80,   73,  134,   91,   82,  135,   92,   74,
       76,  176,  177,   82,  139,  139,   97,   68,   69,   69,
       82,   82,   83,   82,   90,   82,   93,   82,   57,   57,
       99,   73,   91,  100,   94,   92,   95,   74,   76,   84,
       96,   82,   85,   82,   97,   82,   86,   87,   82,  106,
       88,  175,  175,   89,   93,   98,  101,   99,  107,   82,
      100,   94,  102,   82,   95,   82,   82,   84,   96,  108,
       85,   82,  103,  104,   86,   87,  106,   88,   82,   82,
       89,   82,   82,   98,  101,  107,  206,  177,  105,   82,
      102,  207,  177,   82,  131,   69,   69,  108,  138,  103,

      138,  104,  141,   82,  139,  139,  132,  133,   69,   69,
       72,   82,   75,   75,   75,  105,  113,   82,  144,  132,
      142,   82,  145,   82,   76,   82,  131,   69,   69,  149,
      141,  146,   82,  143,  132,   82,   82,   82,  114,   82,
      209,   85,  115,  208,   82,   82,  144,  132,  142,  145,
      116,  150,   76,  117,  143,  118,  149,  119,   82,  146,
      143,  147,  120,  151,   82,   82,  114,  148,  155,   85,
      115,   82,  153,   82,   82,   82,   82,  116,  150,  154,
      117,  143,  118,  152,  119,  124,   82,   82,  147,   82,
      151,  159,   82,   82,  148,  157,  155,   82,  156,  153,

      160,  158,  162,  125,   82,  163,  154,  126,   82,   82,
      152,   82,  161,  165,   82,  127,   82,   82,  128,  159,
      129,  136,  130,  157,   82,  156,  164,  160,  158,   82,
      162,  125,   82,  163,  209,  126,  166,  167,   82,  161,
      208,  165,  127,  183,  174,  128,  174,  129,  142,  130,
      175,  175,   82,  164,  190,   82,   82,  133,   69,   69,
      134,  143,  178,  178,  166,  167,  182,  182,  182,  132,
       82,  183,   82,  184,  188,  185,  142,  186,  187,  193,
      189,   82,  190,   82,   82,   82,  191,   82,  143,  192,
      206,  177,  194,   82,  196,  207,  177,  132,   82,   82,

      184,  188,  185,   82,  186,  187,  193,   82,  189,  195,
       82,   82,  197,  199,  191,  198,  192,  200,   82,  194,
       82,  196,   82,  201,  203,   82,  204,   82,  202,  205,
      205,  205,  134,  210,  178,  178,  195,  211,   82,  197,
      199,   82,   82,  198,  200,  212,   82,   82,   82,  213,
       82,  201,  203,  204,   82,  202,  182,  182,  182,  216,
      210,  214,  215,  218,  211,  219,  220,  217,   82,  223,
       82,   82,  212,  222,   82,  221,   82,  213,   82,   82,
       82,  224,   82,   82,  136,  226,   82,  216,  214,  215,
       82,  218,  219,  220,   82,  217,  223,   82,  205,  205,

      205,  222,  225,  221,   82,   82,  227,  228,  179,  224,
      230,  229,  231,  226,  173,   82,   82,  232,  233,  172,
      234,  235,  171,  170,   82,  169,  237,  238,   82,  225,
      239,  168,   82,  227,   82,  228,   82,  230,  240,  229,
      231,   82,   82,  236,   82,  232,  233,  234,   82,  235,
       82,  110,   82,   82,  237,  238,   82,   82,  239,   82,
      136,  124,   82,  123,  111,  110,  240,   82,   63,   77,
      236,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   60,   60,   60,   60,   60,   60,   60,

       60,   60,   60,   60,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   81,   81,   81,   81,   81,  109,  109,
      109,  112,   67,  112,   67,  112,  112,  112,  112,  112,
      112,  112,  121,   66,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  122,   64,  122,  122,   63,  122,  122,
      122,  122,  122,  122,  137,  241,  137,  137,  140,  140,
      140,  140,  180,  180,  180,  181,  181,  181,  181,   59,
       59,    9,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,

      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241
    } ;

static const flex_int16_t yy_chk[752] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    7,    3,    4,    8,   23,   23,   23,   24,   29,
       29,    7,   25,   24,    8,   33,   26,   35,   26,   26,

       26,   31,   31,   25,   73,   36,   33,   73,   36,   25,
       26,  134,  134,   35,  138,  138,   39,   72,   72,   72,
      240,   36,   33,  238,   35,  237,   37,  235,    3,    4,
       41,   25,   36,   41,   37,   36,   38,   25,   26,   34,
       38,   41,   34,   39,   39,  232,   34,   34,   37,   45,
       34,  174,  174,   34,   37,   40,   42,   41,   46,   38,
       41,   37,   43,   45,   38,  231,   34,   34,   38,   47,
       34,   46,   43,   44,   34,   34,   45,   34,   40,   42,
       34,   43,  230,   40,   42,   46,  176,  176,   44,   47,
       43,  177,  177,   44,   68,   68,   68,   47,   76,   43,

       76,   44,   83,  229,   76,   76,   68,   69,   69,   69,
       75,  226,   75,   75,   75,   44,   57,  224,   86,   69,
       84,  223,   87,  214,   75,   83,  131,  131,  131,   90,
       83,   88,  212,   84,   68,  211,   87,  210,   57,   90,
      209,   85,   57,  208,   84,   86,   86,   69,   84,   87,
       57,   91,   75,   57,   85,   57,   90,   57,   88,   88,
       84,   89,   57,   92,   91,   85,   57,   89,   97,   85,
       57,  203,   95,  200,   92,   89,  193,   57,   91,   96,
       57,   85,   57,   94,   57,   66,   95,   97,   89,   96,
       92,  100,   94,  192,   89,   99,   97,  189,   98,   95,

      101,   99,  103,   66,   98,  104,   96,   66,  188,  101,
       94,  184,  102,  106,   99,   66,  102,  100,   66,  100,
       66,  181,   66,   99,  104,   98,  105,  101,   99,  103,
      103,   66,  106,  104,  180,   66,  107,  108,  105,  102,
      179,  106,   66,  141,  132,   66,  132,   66,  142,   66,
      132,  132,  156,  105,  150,  107,  108,  133,  133,  133,
      135,  142,  135,  135,  107,  108,  139,  139,  139,  133,
      141,  141,  142,  144,  148,  146,  142,  147,  147,  155,
      149,  150,  150,  148,  144,  146,  153,  147,  142,  154,
      206,  206,  157,  155,  159,  207,  207,  133,  154,  157,

      144,  148,  146,  149,  147,  147,  155,  153,  149,  158,
      159,  152,  160,  162,  153,  161,  154,  163,  158,  157,
      160,  159,  162,  164,  166,  151,  167,  163,  165,  175,
      175,  175,  178,  183,  178,  178,  158,  185,  161,  160,
      162,  165,  167,  161,  163,  186,  164,  185,  166,  187,
      183,  164,  166,  167,  186,  165,  182,  182,  182,  194,
      183,  190,  191,  196,  185,  197,  198,  195,  187,  202,
      190,  191,  186,  201,  145,  199,  197,  187,  143,  198,
      140,  204,  196,  202,  137,  215,  194,  194,  190,  191,
      195,  196,  197,  198,  199,  195,  202,  201,  205,  205,

      205,  201,  213,  199,  204,  215,  216,  217,  136,  204,
      219,  218,  220,  215,  130,  216,  213,  221,  222,  129,
      225,  227,  128,  127,  219,  126,  233,  234,  225,  213,
      236,  125,  217,  216,  220,  217,  218,  219,  239,  218,
      220,  222,  221,  228,  227,  221,  222,  225,  233,  227,
      234,  110,  228,  236,  233,  234,  109,   93,  236,   81,
       74,   65,  239,   62,   52,   50,  239,   32,   30,   27,
      228,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  244,  244,  244,  244,  244,  244,  244,

      244,  244,  244,  244,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  246,  246,  246,  246,  246,  247,  247,
      247,  248,   22,  248,   20,  248,  248,  248,  248,  248,
      248,  248,  249,   17,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  250,   16,  250,  250,   13,  250,  250,
      250,  250,  250,  250,  251,    9,  251,  251,  252,  252,
      252,  252,  253,  253,  253,  254,  254,  254,  254,    6,
        5,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,

      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[86] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
    0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexicalAnalyzer.l"
#line 2 "lexicalAnalyzer.l"
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include <math.h>
    #include "syntaxAnalyzer.tab.h"
    
    FILE* fp;
    int lexicalErrors = 0;
    int lineNum = 1;
    char filename[1024];

    void errorHandler();
    void printToken(int tokenID);
    void printNumber(int tokenID);
    int str2Int(char *str);
    double convert2Double(const char *number);

    char str_buf[256];    
    char* str_buf_ptr;
#line 743 "lex.yy.c"

/* Αναγνωριστικά */
/* Απλές σταθερές */
/* Αναπαριστά όλους τους ASCII χαρακτήρες από 32 - 126. */
#line 748 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define INLINE_COMMENTS 2
#define MULTILINE_COMMENTS 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 48 "lexicalAnalyzer.l"


#line 971 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 242 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 672 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 50 "lexicalAnalyzer.l"
{ printToken(T_TYPEDEF); return T_TYPEDEF; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 51 "lexicalAnalyzer.l"
{ printToken(T_CHAR); return T_CHAR; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 52 "lexicalAnalyzer.l"
{ printToken(T_INT); return T_INT; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 53 "lexicalAnalyzer.l"
{ printToken(T_FLOAT); return T_FLOAT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 54 "lexicalAnalyzer.l"
{ printToken(T_CONST); return T_CONST; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 55 "lexicalAnalyzer.l"
{ printToken(T_UNION); return T_UNION; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 56 "lexicalAnalyzer.l"
{ printToken(T_CLASS); return T_CLASS; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 57 "lexicalAnalyzer.l"
{ printToken(T_PRIVATE); return T_PRIVATE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 58 "lexicalAnalyzer.l"
{ printToken(T_PROTECTED); return T_PROTECTED; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 59 "lexicalAnalyzer.l"
{ printToken(T_PUBLIC); return T_PUBLIC; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 60 "lexicalAnalyzer.l"
{ printToken(T_STATIC); return T_STATIC; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 61 "lexicalAnalyzer.l"
{ printToken(T_VOID); return T_VOID; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 62 "lexicalAnalyzer.l"
{ printToken(T_LIST); return T_LIST; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 63 "lexicalAnalyzer.l"
{ printToken(T_CONTINUE); return T_CONTINUE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 64 "lexicalAnalyzer.l"
{ printToken(T_BREAK); return T_BREAK; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 65 "lexicalAnalyzer.l"
{ printToken(T_THIS); return T_THIS; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 66 "lexicalAnalyzer.l"
{ printToken(T_IF); return T_IF; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 67 "lexicalAnalyzer.l"
{ printToken(T_ELSE); return T_ELSE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 68 "lexicalAnalyzer.l"
{ printToken(T_WHILE); return T_WHILE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 69 "lexicalAnalyzer.l"
{ printToken(T_FOR); return T_FOR; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 70 "lexicalAnalyzer.l"
{ printToken(T_RETURN); return T_RETURN; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 71 "lexicalAnalyzer.l"
{ printToken(T_LENGTH); return T_LENGTH; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 72 "lexicalAnalyzer.l"
{ printToken(T_NEW); return T_NEW; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 73 "lexicalAnalyzer.l"
{ printToken(T_CIN); return T_CIN; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 74 "lexicalAnalyzer.l"
{ printToken(T_COUT); return T_COUT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 75 "lexicalAnalyzer.l"
{ printToken(T_MAIN); return T_MAIN; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 80 "lexicalAnalyzer.l"
{ BEGIN(STRING); str_buf_ptr = str_buf;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 81 "lexicalAnalyzer.l"
{ BEGIN(INITIAL); *str_buf_ptr = '\0'; yylval.str = strdup(str_buf); printf("Found string: '%s', id: %d, line: %d\n", str_buf, T_STRING, yylineno); return T_STRING; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 82 "lexicalAnalyzer.l"
{ *str_buf_ptr++ = '\n'; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 83 "lexicalAnalyzer.l"
{ *str_buf_ptr++ = '\f'; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 84 "lexicalAnalyzer.l"
{ *str_buf_ptr++ = '\t'; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 85 "lexicalAnalyzer.l"
{ *str_buf_ptr++ = '\r'; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 86 "lexicalAnalyzer.l"
{ *str_buf_ptr++ = '\b'; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 87 "lexicalAnalyzer.l"
{ *str_buf_ptr++ = '\v'; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 88 "lexicalAnalyzer.l"
{ *str_buf_ptr++ = '\\'; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 89 "lexicalAnalyzer.l"
{ *str_buf_ptr++ = '"'; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 90 "lexicalAnalyzer.l"
{ char *yptr = yytext; while ( *yptr ) *str_buf_ptr++ = *yptr++; }
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 91 "lexicalAnalyzer.l"
{ lineNum++; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 97 "lexicalAnalyzer.l"
{ BEGIN(MULTILINE_COMMENTS); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 98 "lexicalAnalyzer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 99 "lexicalAnalyzer.l"
{ ; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 100 "lexicalAnalyzer.l"
{ ; }
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 101 "lexicalAnalyzer.l"
{ lineNum++; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 103 "lexicalAnalyzer.l"
{ BEGIN(INLINE_COMMENTS); }
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 104 "lexicalAnalyzer.l"
{ BEGIN(INITIAL); lineNum++; } 
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 105 "lexicalAnalyzer.l"
{ ; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 108 "lexicalAnalyzer.l"
{ printToken(T_OROP); yylval.str = strdup(yytext); return T_OROP; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 109 "lexicalAnalyzer.l"
{ printToken(T_ANDOP); yylval.str = strdup(yytext); return T_ANDOP; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 110 "lexicalAnalyzer.l"
{ printToken(T_EQUOP); yylval.str = strdup(yytext); return T_EQUOP; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 111 "lexicalAnalyzer.l"
{ printToken(T_RELOP); yylval.str = strdup(yytext); return T_RELOP; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 112 "lexicalAnalyzer.l"
{ printToken(T_ADDOP); yylval.str = strdup(yytext); return T_ADDOP; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 113 "lexicalAnalyzer.l"
{ printToken(T_MULOP); yylval.str = strdup(yytext); return T_MULOP; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 114 "lexicalAnalyzer.l"
{ printToken(T_NOTOP); yylval.str = strdup(yytext); return T_NOTOP; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 115 "lexicalAnalyzer.l"
{ printToken(T_INCDEC); yylval.str = strdup(yytext); return T_INCDEC; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 116 "lexicalAnalyzer.l"
{ printToken(T_SIZEOP); yylval.str = strdup(yytext); return T_SIZEOP; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 119 "lexicalAnalyzer.l"
{ printToken(T_LPAREN); yylval.str = strdup(yytext); return T_LPAREN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 120 "lexicalAnalyzer.l"
{ printToken(T_RPAREN); yylval.str = strdup(yytext); return T_RPAREN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 121 "lexicalAnalyzer.l"
{ printToken(T_SEMI); yylval.str = strdup(yytext); return T_SEMI; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 122 "lexicalAnalyzer.l"
{ printToken(T_DOT); yylval.str = strdup(yytext); return T_DOT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 123 "lexicalAnalyzer.l"
{ printToken(T_COMMA); yylval.str = strdup(yytext); return T_COMMA; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 124 "lexicalAnalyzer.l"
{ printToken(T_ASSIGN); yylval.str = strdup(yytext); return T_ASSIGN; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 125 "lexicalAnalyzer.l"
{ printToken(T_COLON); yylval.str = strdup(yytext); return T_COLON; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 126 "lexicalAnalyzer.l"
{ printToken(T_LBRACK); yylval.str = strdup(yytext); return T_LBRACK; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 127 "lexicalAnalyzer.l"
{ printToken(T_RBRACK); yylval.str = strdup(yytext); return T_RBRACK; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 128 "lexicalAnalyzer.l"
{ printToken(T_REFER); yylval.str = strdup(yytext); return T_REFER; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 129 "lexicalAnalyzer.l"
{ printToken(T_LBRACE); yylval.str = strdup(yytext); return T_LBRACE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 130 "lexicalAnalyzer.l"
{ printToken(T_RBRACE); yylval.str = strdup(yytext); return T_RBRACE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 131 "lexicalAnalyzer.l"
{ printToken(T_METH); yylval.str = strdup(yytext); return T_METH; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 132 "lexicalAnalyzer.l"
{ printToken(T_INP); yylval.str = strdup(yytext); return T_INP; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 133 "lexicalAnalyzer.l"
{ printToken(T_OUT); yylval.str = strdup(yytext); return T_OUT; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 136 "lexicalAnalyzer.l"
{ printToken(T_LISTFUNC); yylval.str = strdup(yytext); return T_LISTFUNC; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 137 "lexicalAnalyzer.l"
{ printNumber(T_ICONST); yylval.integer = str2Int(yytext); return T_ICONST; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 138 "lexicalAnalyzer.l"
{ printNumber(T_FCONST); yylval.real = convert2Double(yytext); return T_FCONST; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 139 "lexicalAnalyzer.l"
{ printToken(T_CCONST); yylval.str = strdup(yytext); return T_CCONST; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 141 "lexicalAnalyzer.l"
{ }
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 143 "lexicalAnalyzer.l"
{ lineNum++; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 145 "lexicalAnalyzer.l"
{ return T_CCONST; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 147 "lexicalAnalyzer.l"
{ return T_CCONST; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 149 "lexicalAnalyzer.l"
{ return T_CCONST; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 151 "lexicalAnalyzer.l"
{ return T_CCONST; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 153 "lexicalAnalyzer.l"
{ return T_CCONST; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 155 "lexicalAnalyzer.l"
{ return T_CCONST; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 158 "lexicalAnalyzer.l"
{ printToken(T_ID); yylval.str = strdup(yytext); return T_ID; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(INLINE_COMMENTS):
case YY_STATE_EOF(MULTILINE_COMMENTS):
#line 160 "lexicalAnalyzer.l"
{ printf("Found token: '%s', id: %d, line: %d\n", "EOF", T_EOF, yylineno); return T_EOF; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 163 "lexicalAnalyzer.l"
{ lexicalErrors++; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 165 "lexicalAnalyzer.l"
ECHO;
	YY_BREAK
#line 1474 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 242 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 242 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 241);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 165 "lexicalAnalyzer.l"



void printToken(int tokenID) {
    printf("Found token: '%s', id: %d, line: %d\n", yytext, tokenID, yylineno);
}


void printNumber(int tokenID) {
    int number, base;

    base = 10;
    if(strncmp(yytext, "0H", 2) == 0) {
        base = 16;
        number = (int) strtol(&yytext[2], NULL, base); // Μετατροπή δεκαεξαδικού αριθμού σε δεκαδικό ακέραιο.
    } else if(strncmp(yytext, "0B", 2) == 0) {
        base = 2;
        number = (int) strtol(&yytext[2], NULL, base); // Μετατροπή δυαδικού αριθμού σε δεκαδικό ακέραιο.
    } 
    else number = (int) strtol(yytext, NULL, base);

    printf("Found number: '%d', from base: %d, id: %d, line: %d\n", number, base, tokenID, yylineno);
}


// Μετατροπή αριθμών σε ακέραιους δεκαδικούς.
int str2Int(char *str) {
    // Μετατροπή δεκαεξαδικού αριθμού σε δεκαδικό ακέραιο.
    if(strncmp(str, "0H", 2) == 0) {
        return (int) strtol(&str[2], NULL, 16);
    }

    // Μετατροπή δυαδικού αριθμού σε δεκαδικό ακέραιο.
    if(strncmp(str, "0B", 2) == 0) {
        return (int) strtol(&str[2], NULL, 2);
    }

    return (int) strtol(str, NULL, 10);
}

double convertFractionalPart(const char *fraction, int base) {
    double result = 0.0;
    int len = strlen(fraction);

    // Μετατρέπουμε κάθε ψηφίο, ανάλογα με τη βάση του, σε δεκαδικό και επιστρέφουμε το αποτέλεσμα.
    for (int i = 0; i < len; i++) {
        if (fraction[i] >= '0' && fraction[i] <= '9') {
            result += (fraction[i] - '0') / pow(base, i + 1);
        } else if (fraction[i] >= 'A' && fraction[i] <= 'F') {
            result += (10 + fraction[i] - 'A') / pow(base, i + 1);
        } else if (fraction[i] >= 'a' && fraction[i] <= 'f') {
            result += (10 + fraction[i] - 'a') / pow(base, i + 1);
        }
    }
    
    return result;
}

double convertExponentialPart(const char *str) {
    return strtod(str, NULL); // Μετατρέπουμε τον εκθετικό αριθμό σε double.
}

double convert2Double(const char *number) {
    char *endPtr;
    double result = 0.0;

    // Ελέγχουμε τον τύπο του αριθμού και το μετατρέπουμε σε double.
    if (strncmp(number, "0H", 2) == 0) {
        // Δεκαεξαδικός.
        result = strtod(number + 2, &endPtr);
    } else if (strncmp(number, "0B", 2) == 0) {
        // Δυαδικός.
        result = strtoul(number + 2, &endPtr, 2);
    } else {
        // Δεκαδικός.
        result = strtod(number, &endPtr);
    }

    // Διαχειριζόμαστε το κλασματικό μέρος.
    if (*endPtr == '.') {
        result += convertFractionalPart(endPtr + 1, (*number == '0' && *(number + 1) == 'X') ? 16 : 10); // Μετατρέπουμε το κλασματικό μέρος, ανάλογα με τη βάση του, σε δεκαδικό.
        endPtr = strchr(endPtr + 1, 'E'); // Παίρνουμε το κλασματικό μέρος, μέχρι να βρούμε το εκθετικό.
    }

    // Μετατρέπουμε τον εκθετικό σε double και το προσαρμόζουμε στο αποτέλεσμα που έχουμε.
    if (endPtr && *endPtr == 'E') {
        result *= pow(10, convertExponentialPart(endPtr + 1));
    }

    return result;
}

